api/urls.py
from django.conf.urls import patterns, include, url
from rest_framework import routers
from api import views

router = routers.DefaultRouter()
router.register(r'tweets', views.TweetViewSet)
router.register(r'users', views.MyUserViewSet)

urlpatterns = [
	url(r'^', include(router.urls)),
	url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

followx/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from app.views import Home, AddFavorite, ListaRt, Timeline, signup, RemoveFavorite, AddFollow, RemoveFollow, login, logout, RemoveRetweet, AddRetweet, new_tweet, update_tweet, delete_tweet
from django.conf import settings
from django.contrib.auth.decorators import login_required
from api import urls as api_urls


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', login_required(Home.as_view()), name='home'),
    url(r'^lista_rt/$',ListaRt.as_view(), name="lista_rt"),
    url(r'^timeline/$', Timeline.as_view(), name="timeline"),
    url(r'^add_follow/(?P<id>\d{1,})/$', AddFollow.as_view(), name="add_follow"),
    url(r'^remove_follow/(?P<id>\d{1,})/$', RemoveFollow.as_view(), name="remove_follow"),
    url(r'^accounts/login/', login, name="login"),
    url(r'^logout/', logout, name="logout"),
    url(r'^signup/', signup, name="signup"),
    url(r'^new_tweet/$',new_tweet, name='new_tweet'),
    url(r'^update_tweet/(?P<id_tweet>\d{1,})/$', update_tweet, name='update_tweet'),
    url(r'^delete_tweet/(?P<id_tweet>\d{1,})/$', delete_tweet, name='delete_tweet'),
    url(r'^add_favorite/(?P<id_tweet>\d{1,})/$', AddFavorite.as_view(), name='add_favorite'),
    url(r'^remove_favorite/(?P<id_tweet>\d{1,})/$', RemoveFavorite.as_view(), name='remove_favorite'),
    url(r'^add_retweet/(?P<id_tweet>\d{1,})/$', AddRetweet.as_view(), name='add_retweet'),
    url(r'^remove_retweet/(?P<id_tweet>\d{1,})/$', RemoveRetweet.as_view(), name='remove_retweet'),
    url(r'^api/', include(api_urls), name='api_urls')
]

app/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractBaseUser, BaseUserManager
from django.conf import settings
from string import join
# Create your models here.

class Tag(models.Model):
    tag = models.CharField(max_length=50)

    def __unicode__(self):
        return self.tag

class Tweet(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    tweet = models.CharField(max_length=140)
    date = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(Tag)   
    user_favs = models.ManyToManyField(settings.AUTH_USER_MODEL, through = 'app.Favorite', related_name = 'user_favs')
    user_rts = models.ManyToManyField(settings.AUTH_USER_MODEL, through = 'app.Retweet', related_name = 'user_rts')

    def __unicode__(self):
        return self.tweet 

    def tags_(self):
        lst = [x[1] for x in self.tags.values_list()]
        return str(join(lst, ', '))

    # def user_favs_(self):
    #     lst = [x[1] for x in self.user_favs.values_list()]
    #     return str(join(lst, ', '))

    # def user_rts_(self):
    #     lst = [x[1] for x in self.user_rts.values_list()]
    #     return str(join(lst,', '))

class Favorite(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    tweet = models.ForeignKey('app.Tweet')
    date = models.DateTimeField(auto_now_add=True) 

class Retweet(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    tweet = models.ForeignKey('app.Tweet')
    date = models.DateTimeField(auto_now_add=True)

class MyUserManager(BaseUserManager):
    def _create_user(self, usuario, email, password, is_superuser, is_active, is_staff):

        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            usuario=usuario,
            email=self.normalize_email(email),
            password=password,
            is_active=is_active,
            is_superuser=is_superuser,
            is_staff=is_staff
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    def create_user(self, usuario, email, password=None):
    	return self._create_user(usuario, email, password, False, True, False)

    def create_superuser(self, usuario, email, password):
        return self._create_user(usuario, email, password, True, True, True)

class MyUser(AbstractBaseUser):

    first_name = models.CharField(max_length=200, blank=True, help_text="The first name of the user.")
    last_name = models.CharField(max_length=200, blank=True, help_text="The last name of the user.")
    follow = models.ManyToManyField('self')
    usuario = models.CharField(max_length=40, unique=True)
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        help_text="The email and identifier of the user"
    )
    is_active = models.BooleanField(
        default=True, 
        help_text="Determines whether the user is active or not. ",
        verbose_name="Active"
    )
    is_staff = models.BooleanField(
    	default=True,
    	help_text="Designates where the user will have acces to the admin interface",
    	verbose_name='Staff Status')
    is_superuser = models.BooleanField(
        default=True, 
        help_text="CAUTION - enabling this gives the user full admin access and access to the entire database. Only for ArcCore admins.",
        verbose_name="Superuser"
    )

    objects = MyUserManager()

    USERNAME_FIELD = 'usuario'
    REQUIRED_FIELDS = ['email']


    def follow_(self):
        lst =[x[1] for x in self.follow.values_list()]
        return str(join(lst, ', '))


    def get_full_name(self):
        #If the full name is not specified, return email
        if self.first_name == "" and self.last_name == "":
            return self.email
        else:
            return self.first_name + " " + self.last_name
    get_full_name.short_description = 'Name'

    def get_short_name(self):
        return self.first_name

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        return True

templates/home.html
{% extends 'bases/base.html' %}
{% load staticfiles %}
{% block content %}
<div class='col-md-4'>
<div class='well' id='create'>
	<form class="form-inline" method="POST" action="{% url 'new_tweet' %}">
	{% csrf_token %}
	<div class="form-group">
	<input type="text" placeholder="Que pedo..." class="form-control" style="width:290px" name="tweet">
	</div>
	<input type="submit" name="submit" class="btn btn-default" value="Tweet">
</form>
</div>

{% for user in users %}
{% for tweet in user.tweet_set.all %}
{% if tweet in trends %}
<div class='well'>
{{ tweet }}
</div>
{% endif %}
{% endfor %}
{% endfor %}

{% for user in users %}
{% for tweet in user.tweet_set.all %}
<div class='well'>
<p><strong>{{ tweet }}</strong> @ {{ user }}</p> 
<p>{{ tweet.date }}

  <a href="update_tweet/{{ tweet.id }}"><i class="glyphicon glyphicon-pencil"></i></a>
  <a href="delete_tweet/{{ tweet.id }}"><i class="glyphicon glyphicon-remove"></i></a>
  
  {% if tweet.id in favorites %} 
  <a href="remove_favorite/{{ tweet.id }}"><i class="glyphicon glyphicon-star" style="color:yellow"></i></a> 
  {% else %}
  <a href="add_favorite/{{ tweet.id }}"><i class="glyphicon glyphicon-star"></i></a>
  {% endif %}
    <i class="badge"> {{ tweet.user_favs.count }}</i></a>

  {% if tweet.id in retweets %} 
  <a href="remove_retweet/{{ tweet.id }}"><i class="glyphicon glyphicon-retweet" style="color:yellow"></i></a> 
  {% else %}
  <a href="add_retweet/{{ tweet.id }}"><i class="glyphicon glyphicon-retweet"></i></a>
  {% endif %}
</div>
{% endfor %}
{% endfor %}




</div>
{% endblock %}

templates/lista_rt.html
{% extends 'bases/base.html' %}
{% load staticfiles %}
{% block content %}
<div class='col-md-4'>
{% for tweet in retweets %}
<div class='well'>
<p>{{tweet.tweet}} @ {{tweet.tweet.user}}</p>
{{tweet.date}}
</div>
{% endfor %}

</div>
{% endblock %}

templates/login.html
{% extends 'bases/base.html' %}
{% load staticfiles %}
{% block content %}
<div class='col-md-4'>
<div class='well'>
  <form method="POST" class="form-inline">
  {% csrf_token %}
  	<div class="form-group">
<input type="text" placeholder="Usuario" class="form-control" style="width:120px" name="usuario">
<input type="text" placeholder="Contraseña" class="form-control" style="width:120px" name="password">
</div>
  <input type="submit" value="login" class="btn btn-default" style="width:100px">
  </form>
  </div>
  </div>
{% endblock %}

templates/new_tweet.html
<form method="POST">
{% csrf_token %}
<input type="text" name="tweet">
<input type="submit">
</form>

templates/signup.html
{% extends 'bases/base.html' %}
{% load staticfiles %}
{% block content %}
<div class='col-md-4'>
<div class='well'>
  <form method="POST" class="form-inline" style="text-align:center">
  {% csrf_token %}
  	<div class="form-group" >
<p><input type="text" placeholder="Usuario" class="form-control" style="width:240px" name="usuario">  </p>
 <p><input type="text" placeholder="email" class="form-control" style="width:240px" name="email">  </p>
<p> <input type="text" placeholder="Contraseña" class="form-control" style="width:118px" name="password1">
<input type="text" placeholder="Contraseña" class="form-control" style="width:118px;" name="password2"> </p>

</div>
  <input type="submit" value="signup" class="btn btn-default" style="width:240px">
  </form>
  </div>
  </div>
{% endblock %}

templates/timeline.html
{% extends 'bases/base.html' %}
{% load staticfiles %}
{% block content %}
<div class='col-md-4'>
{% for tweet in timeline %}
<div class='well'>
<p> {{tweet}} by @ {{tweet.user}} <p>
<p> {{tweet.date}}
</div>
{% endfor %}

</div>
{% endblock %}

templates/update_tweet.html
<form method="POST">
{% csrf_token %}
{{ form }}
<input type="submit"value="Submit">
</form>